# Generated by Django 4.2.7 on 2026-03-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_add_runner_stable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Event date parsed from homepage'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Event name as found on timataka.net homepage', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(help_text='URL to the event page on timataka.net', unique=True),
        ),
    ]
