# Generated by Django 4.2.7 on 2026-03-07 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0013_racesurfacekeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceDistanceKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.CharField(help_text='Word or text snippet to match against race name/description/location.', max_length=120)),
                ('normalized_snippet', models.CharField(db_index=True, editable=False, max_length=120, unique=True)),
                ('distance_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower value means higher priority when multiple rules match.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'normalized_snippet'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='races_raced_is_acti_ae0b5d_idx'), models.Index(fields=['distance_km'], name='races_raced_distanc_4e0d79_idx')],
            },
        ),
    ]
