# Generated by Django 4.2.7 on 2026-03-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0014_racedistancekeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_stable_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('alias_runner_id', models.IntegerField(blank=True, db_index=True, help_text='Legacy runner numeric ID, if applicable.', null=True, unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_runner', models.ForeignKey(help_text='Default profile this alias should resolve to.', on_delete=django.db.models.deletion.CASCADE, related_name='canonical_aliases', to='races.runner')),
                ('source_runner', models.ForeignKey(blank=True, help_text='Linked duplicate profile (can be null after merge/delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_aliases', to='races.runner')),
            ],
            options={
                'ordering': ['alias_stable_id'],
                'indexes': [models.Index(fields=['canonical_runner', 'is_active'], name='races_runne_canonic_144689_idx'), models.Index(fields=['source_runner', 'is_active'], name='races_runne_source__6014f0_idx')],
            },
        ),
    ]
