# Generated by Django 4.2.7 on 2026-03-17 17:23

import unicodedata
from django.db import migrations, models


DEFAULT_DISCIPLINE_KEYWORDS = [
    ("hjól", "biking", 10),
    ("bike", "biking", 11),
    ("cycling", "biking", 12),
    ("criterium", "biking", 13),
    ("mtb", "biking", 14),
    ("downhill", "biking", 15),
    ("townhill", "biking", 16),
    ("time trial", "biking", 17),
    ("tour de", "biking", 18),
    ("xc", "biking", 19),
    ("dh", "biking", 20),
    ("ski", "skiing", 30),
    ("skíða", "skiing", 31),
    ("skiganga", "skiing", 32),
    ("skimarathon", "skiing", 33),
    ("sleðahunda", "skiing", 34),
    ("strandagangan", "skiing", 35),
    ("fjarðargangan", "skiing", 36),
    ("hlaup", "running", 100),
    ("run", "running", 101),
    ("skokk", "running", 102),
    ("marathon", "running", 103),
    ("mara", "running", 104),
    ("trail", "running", 105),
    ("ultra", "running", 106),
]


def _normalize_text(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", (value or "").casefold())
    return "".join(char for char in normalized if not unicodedata.combining(char))


def _infer_from_rules(text: str, rules: list[tuple[str, str]]) -> str | None:
    for snippet, discipline in rules:
        if snippet and snippet in text:
            return discipline
    return None


def _infer_event_discipline(name: str, url: str, rules: list[tuple[str, str]], current: str) -> str:
    text = _normalize_text(f"{name} {url}")
    matched = _infer_from_rules(text, rules)
    if matched:
        return matched

    biking_keywords = ["hjol", "bike", "cycling", "criterium", "mtb", "downhill", "townhill", "time trial", "tour de", "brekkusprett", "dh", "xc"]
    skiing_keywords = ["ski", "skiða", "skiganga", "skimarathon"]
    running_keywords = ["hlaup", "run", "skokk", "marathon", "mara", "trail", "ultra", "half", "5k", "10k"]

    if any(keyword in text for keyword in biking_keywords):
        return "biking"
    if any(keyword in text for keyword in skiing_keywords):
        return "skiing"
    if any(keyword in text for keyword in running_keywords):
        return "running"
    return current or "unknown"


def _infer_race_discipline(race, rules: list[tuple[str, str]], event_discipline: str) -> str:
    text = _normalize_text(
        " ".join(
            [
                str(getattr(race, "name", "") or ""),
                str(getattr(race, "description", "") or ""),
                str(getattr(race, "location", "") or ""),
                str(getattr(race, "organizer", "") or ""),
                str(getattr(race, "source_url", "") or ""),
                str(getattr(race, "results_url", "") or ""),
            ]
        )
    )
    matched = _infer_from_rules(text, rules)
    if matched:
        return matched

    race_type = (getattr(race, "race_type", "") or "").strip().lower()
    if race_type in {"marathon", "half_marathon", "10k", "5k", "trail", "ultra"}:
        return "running"

    biking_keywords = ["hjol", "bike", "cycling", "criterium", "mtb", "downhill", "townhill", "time trial", "tour de", "brekkusprett", "dh", "xc", "bmx"]
    skiing_keywords = ["ski", "skiða", "skiganga", "skimarathon"]
    running_keywords = ["hlaup", "run", "skokk", "marathon", "mara", "trail", "ultra", "half", "5k", "10k"]

    if any(keyword in text for keyword in biking_keywords):
        return "biking"
    if any(keyword in text for keyword in skiing_keywords):
        return "skiing"
    if any(keyword in text for keyword in running_keywords):
        return "running"
    if event_discipline in {"running", "biking", "skiing"}:
        return event_discipline
    return getattr(race, "discipline", "unknown") or "unknown"


def seed_and_backfill_disciplines(apps, schema_editor):
    DisciplineKeyword = apps.get_model("races", "DisciplineKeyword")
    Event = apps.get_model("races", "Event")
    Race = apps.get_model("races", "Race")

    for snippet, discipline, priority in DEFAULT_DISCIPLINE_KEYWORDS:
        normalized_snippet = _normalize_text(snippet).strip()
        DisciplineKeyword.objects.update_or_create(
            normalized_snippet=normalized_snippet,
            defaults={
                "snippet": snippet,
                "discipline": discipline,
                "priority": priority,
                "is_active": True,
                "notes": "Seeded default discipline keyword",
            },
        )

    rules = list(
        DisciplineKeyword.objects.filter(is_active=True)
        .order_by("priority", "id")
        .values_list("normalized_snippet", "discipline")
    )

    event_discipline_by_id = {}
    for event in Event.objects.all().order_by("id"):
        discipline = _infer_event_discipline(event.name, event.url, rules, event.discipline)
        if event.discipline != discipline:
            event.discipline = discipline
            event.save(update_fields=["discipline"])
        event_discipline_by_id[event.id] = discipline

    for race in Race.objects.select_related("event").all().order_by("id"):
        event_discipline = event_discipline_by_id.get(race.event_id, "unknown")
        discipline = _infer_race_discipline(race, rules, event_discipline)
        if race.discipline != discipline:
            race.discipline = discipline
            race.save(update_fields=["discipline"])

    for event in Event.objects.all().order_by("id"):
        race_disciplines = list(
            Race.objects.filter(event_id=event.id)
            .exclude(discipline="unknown")
            .values_list("discipline", flat=True)
        )
        if not race_disciplines:
            continue
        counts = {}
        for discipline in race_disciplines:
            counts[discipline] = counts.get(discipline, 0) + 1
        next_discipline = sorted(counts.items(), key=lambda item: (-item[1], item[0]))[0][0]
        if event.discipline != next_discipline:
            event.discipline = next_discipline
            event.save(update_fields=["discipline"])


def remove_seeded_keywords(apps, schema_editor):
    DisciplineKeyword = apps.get_model("races", "DisciplineKeyword")
    normalized_snippets = [_normalize_text(snippet).strip() for snippet, _, _ in DEFAULT_DISCIPLINE_KEYWORDS]
    DisciplineKeyword.objects.filter(normalized_snippet__in=normalized_snippets).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0015_runneralias'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.CharField(help_text='Word or text snippet to match against race/event name, description, location, organizer, or URL.', max_length=120)),
                ('normalized_snippet', models.CharField(db_index=True, editable=False, max_length=120, unique=True)),
                ('discipline', models.CharField(choices=[('running', 'Running'), ('biking', 'Biking'), ('skiing', 'Skiing'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower value means higher priority when multiple rules match.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'normalized_snippet'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='discipline',
            field=models.CharField(choices=[('running', 'Running'), ('biking', 'Biking'), ('skiing', 'Skiing'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Broad sport classification used for public filtering and race comparisons.', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='discipline',
            field=models.CharField(choices=[('running', 'Running'), ('biking', 'Biking'), ('skiing', 'Skiing'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Broad sport classification used for public filtering and race comparisons.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['discipline'], name='races_event_discipl_6d67fe_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['discipline'], name='races_race_discipl_e839f0_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinekeyword',
            index=models.Index(fields=['discipline'], name='races_disci_discipl_bca930_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinekeyword',
            index=models.Index(fields=['is_active', 'priority'], name='races_disci_is_acti_00628c_idx'),
        ),
        migrations.RunPython(seed_and_backfill_disciplines, remove_seeded_keywords),
    ]
