# Generated by Django 4.2.7 on 2026-03-17 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0016_disciplinekeyword_event_discipline_race_discipline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceCorrectionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_surface_type', models.CharField(choices=[('road', 'Road'), ('trail', 'Trail'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('current_distance_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('current_discipline', models.CharField(choices=[('running', 'Running'), ('biking', 'Biking'), ('skiing', 'Skiing'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('current_race_type', models.CharField(choices=[('marathon', 'Marathon'), ('half_marathon', 'Half Marathon'), ('10k', '10K'), ('5k', '5K'), ('trail', 'Trail Run'), ('ultra', 'Ultra Marathon'), ('other', 'Other')], default='other', max_length=20)),
                ('suggested_surface_type', models.CharField(blank=True, choices=[('road', 'Road'), ('trail', 'Trail'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], help_text='Leave blank if no surface correction is being suggested.', max_length=20)),
                ('suggested_distance_km', models.FloatField(blank=True, help_text='Leave empty if no distance correction is being suggested.', null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('suggested_discipline', models.CharField(blank=True, choices=[('running', 'Running'), ('biking', 'Biking'), ('skiing', 'Skiing'), ('unknown', 'Unknown')], help_text='Leave blank if no discipline correction is being suggested.', max_length=20)),
                ('suggested_race_type', models.CharField(blank=True, choices=[('marathon', 'Marathon'), ('half_marathon', 'Half Marathon'), ('10k', '10K'), ('5k', '5K'), ('trail', 'Trail Run'), ('ultra', 'Ultra Marathon'), ('other', 'Other')], help_text='Leave blank if no race type correction is being suggested.', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('submitter_name', models.CharField(blank=True, max_length=120)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_suggestions', to='races.race')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='races_racec_status_763e13_idx'), models.Index(fields=['race', 'status'], name='races_racec_race_id_3c9ef4_idx')],
            },
        ),
    ]
