# Generated by Django 4.2.7 on 2026-03-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0017_racecorrectionsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racecorrectionsuggestion',
            name='current_distance_km',
            field=models.FloatField(),
        ),
    ]
